Iter5
radiophysiker/link_shortener pull request #4
Opened 2024-05-01 15:10 UTC by radiophysiker

2024-05-04 15:58 UTC, s-shpak requested changes

2024-05-04 15:58 UTC, s-shpak commented on internal/app/app.go
> +		log.Fatalf("cannot load config! %s", err)
Посмотри это видео про обработку ошибок и поправь код, пожалуйста: https://app.pachca.com/chats/9180496?message=234290731

2024-05-04 15:58 UTC, s-shpak commented on internal/config/config.go
> +func (c *Config) GetServerPort() string {
В го не принято использовать геттеры и сеттеры (только в некоторых случаях, при работе с мьютексами, например)

2024-05-04 15:58 UTC, s-shpak commented on internal/config/config.go
> +	"github.com/caarlos0/env/v10"
Есть 11-ая версия

2024-05-04 15:58 UTC, s-shpak commented on internal/handlers/create_url.go
> +		w.WriteHeader(http.StatusInternalServerError)
`InternalServerError` стоит логировать

2024-05-04 15:58 UTC, s-shpak commented on internal/handlers/create_url.go
> +	_, err = w.Write([]byte(baseURL + "/" + shortURL))
Лучше использовать https://pkg.go.dev/net/url#JoinPath

2024-05-04 15:58 UTC, s-shpak commented on internal/handlers/get_full_url.go
> +	fullURL, err := h.URLUseCase.GetFullURL(shortURL)
См. видео

2024-05-04 15:58 UTC, s-shpak commented on internal/handlers/url_handlers.go
> +func (h *URLHandler) RegisterRoutes(r chi.Router) {
Лучше, чтобы не хендлеры зависили от `chi`, а пакет с роутером от хендлеров

2024-05-04 15:58 UTC, s-shpak commented on internal/repository/storage.go
> +	s.urls[url.ShortURL] = fullURL
Что если такой `short URL` уже существует ?

2024-05-04 15:58 UTC, s-shpak commented on internal/usecases/url_test.go
> +	mocksRepoURL.
Может тогда стоит протестировать и ошибки ?

2024-05-04 15:58 UTC, s-shpak commented on internal/utils/get_short_random_string.go
> +	countOfCharacters = 8
Лучше это значение передавать функции, т.к. оно может меняться

2024-05-04 15:58 UTC, s-shpak commented on internal/utils/get_short_random_string.go
> +	var encodedBuilder strings.Builder
Не вижу смысла использовать `strings.Builder`. Лучше просто инициализировать слайс и заполнять его по индексам

2024-05-06 22:36 UTC, radiophysiker commented on internal/app/app.go
> +		log.Fatalf("cannot load config! %s", err)
Спасибо поправил. Правда не уверен, что правильно сделал по теме обработки ошибок

2024-05-06 22:36 UTC, radiophysiker commented on internal/config/config.go
> +func (c *Config) GetServerPort() string {
Поправил

2024-05-06 22:36 UTC, radiophysiker commented on internal/config/config.go
> +	"github.com/caarlos0/env/v10"
Обновил

2024-05-06 22:37 UTC, radiophysiker commented on internal/handlers/create_url.go
> +		w.WriteHeader(http.StatusInternalServerError)
Логирование будет во втором спринте. Поэтому не все логировал

2024-05-06 22:38 UTC, radiophysiker commented on internal/handlers/create_url.go
> +	_, err = w.Write([]byte(baseURL + "/" + shortURL))
Спасибо. Поправил

2024-05-06 22:38 UTC, radiophysiker commented on internal/handlers/url_handlers.go
> +func (h *URLHandler) RegisterRoutes(r chi.Router) {
Поменял

2024-05-06 22:54 UTC, radiophysiker commented on internal/repository/storage.go
> +	s.urls[url.ShortURL] = fullURL
добавил проверку в usecase

2024-05-10 15:49 UTC, radiophysiker commented on internal/usecases/url.go
> +	err := us.urlRepository.Save(url)
Добавил метод retryCreateShortURL

2024-05-10 15:50 UTC, radiophysiker commented on internal/handlers/create_url.go
> +	fmt.Println(baseURL)
осталось в коде случайно... Удалил

2024-05-10 15:50 UTC, radiophysiker commented on internal/usecases/mocks/fs.go
дропнул моки. Тестирую только  in-memory хранилище

2024-05-10 15:51 UTC, radiophysiker commented on internal/repository/storage.go
> +func (s URLStorage) IsFullURLExists(fullURL FullURL) bool {
Удалил. Сделал проверку IsShortURLExists

2024-05-10 15:52 UTC, radiophysiker commented on internal/handlers/create_url.go
> +		w.WriteHeader(http.StatusInternalServerError)
Добавил логирование. Добавил WriteErrorWithCannotWriteResponse в utils чтобы код не дублировался код

2024-05-11 13:22 UTC, s-shpak approved these changes

2024-05-14 08:28 UTC, merged